version: '3'
services:
  frontend:
    build:
      context: ./stream-loop
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/stream-loop
      - JWT_SECRET=U3RyZWFtUGxheWVyQ3JlYXRlZEJ5RGVlcGFrS3VtYXI=
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: